import { Injectable } from "@nestjs/common"

import { PrismaService } from "../../prisma/prisma.service"

export type ProvisionInput = {
  /** Generated by the caller so the tenant context can be opened before the rows exist. */
  orgId: string
  name: string
  slug: string
  domain: string | null
  owner: { userId: string; displayName: string }
  teams: readonly string[]
  now: Date
}

export type ProvisionResult =
  | { outcome: "created"; membershipId: string }
  /** The slug is in use now, or was once — a released slug is never reused (TENANCY.md §2). */
  | { outcome: "slug-taken" }

/**
 * The provisioning transaction (TENANCY.md §4): the organization, its owner's
 * membership, the picker's projection row and the default teams — or nothing.
 *
 * Runs inside `runAsTenant(orgId)`, so the tenant-owned rows are written under
 * RLS exactly as any request would write them. Uniqueness is decided under a
 * transaction-scoped advisory lock on the slug, because "never reuse" spans two
 * tables and no single constraint can hold it (handoff: slug reuse race).
 */
@Injectable()
export class OrganizationProvisioningRepository {
  constructor(private readonly prisma: PrismaService) {}

  provision(input: ProvisionInput): Promise<ProvisionResult> {
    return this.prisma.transaction(async (tx) => {
      // Serialises everyone who wants THIS slug — provisioning and slug change
      // alike — until the transaction ends. Released with it; never leaks.
      await tx.$executeRaw`SELECT pg_advisory_xact_lock(hashtext(${`slug:${input.slug}`}))`

      const [current, retired] = await Promise.all([
        tx.organization.findUnique({ where: { slug: input.slug }, select: { id: true } }),
        tx.organizationSlugHistory.findUnique({ where: { slug: input.slug }, select: { id: true } }),
      ])
      if (current !== null || retired !== null) return { outcome: "slug-taken" }

      await tx.organization.create({
        data: { id: input.orgId, name: input.name, slug: input.slug, domain: input.domain },
      })
      const membership = await tx.membership.create({
        data: {
          orgId: input.orgId,
          userId: input.owner.userId,
          role: "OWNER",
          status: "ACTIVE",
          kind: "HUMAN",
          displayName: input.owner.displayName,
          joinedAt: input.now,
        },
        select: { id: true },
      })
      // Derived, written with its source (ADR-0022).
      await tx.userOrgIndex.create({
        data: {
          userId: input.owner.userId,
          orgId: input.orgId,
          roleForDisplay: "OWNER",
          statusForDisplay: "ACTIVE",
          orgSlug: input.slug,
          orgName: input.name,
          orgStatus: "ACTIVE",
        },
      })
      await tx.team.createMany({ data: input.teams.map((name) => ({ orgId: input.orgId, name })) })

      return { outcome: "created", membershipId: membership.id }
    })
  }

  /** Current and retired slugs alike — the live check behind the signup form. */
  async isSlugTaken(slug: string): Promise<boolean> {
    const [current, retired] = await Promise.all([
      this.prisma.db.organization.findUnique({ where: { slug }, select: { id: true } }),
      this.prisma.db.organizationSlugHistory.findUnique({ where: { slug }, select: { id: true } }),
    ])
    return current !== null || retired !== null
  }
}
